freebsd_14_amd64_instance:
  image: freebsd-14-3-release-amd64-ufs
  cpu: 2
  memory: 4G

archlinux_x86_64_instance: &archlinux_x86_64_instance
  image: archlinux:latest
  cpu: 2
  memory: 4G

build_freebsd_14_amd64_task:
  freebsd_instance:
    image: freebsd-14-3-release-amd64-ufs
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for FreeBSD:14:amd64"
  alias: data
  install_script:
    - pkg update
    - pkg install -y git tree squashfs-tools
    - ./bootstrap.sh
  checkout_script:
    - ./checkout.sh
  build_script:
    - make install
  package_script:
    - mkdir -p artifacts/FreeBSD/14/amd64
    - tar -C / -cJf artifacts/FreeBSD/14/amd64/system.txz /System
    - export TIMESTAMP=$(date +%y%m%d%H%M%S)
    - mksquashfs /System artifacts/FreeBSD/14/amd64/Gershwin-FreeBSD-${TIMESTAMP}.squashfs -comp xz -b 1M
    - find /System -type f -perm -111 -exec sh -c 'ldd "$1" 2>/dev/null | awk "/=>/ {print \$3}" | xargs -n1 pkg which 2>/dev/null | grep package | awk "{print \$6}" | sed "s/-[^-]*\$//"' sh {} \; | sort -u > artifacts/FreeBSD/14/amd64/Gershwin-FreeBSD-${TIMESTAMP}.dependencies
  publish_script:
    - cd artifacts/FreeBSD/14/amd64
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin System for FreeBSD 14 amd64' ./ > ./index.html
    - echo "Branch-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/FreeBSD/14/amd64/index.html?branch=${CIRRUS_BRANCH}"
    - echo "Commit-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/FreeBSD/14/amd64/index.html?sha=${CIRRUS_CHANGE_IN_REPO}"
  system_artifacts:
    path: "artifacts/FreeBSD/14/amd64/**/*"

build_archlinux_x86_64_task:
  container:
    image: archlinux:latest
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for Arch Linux (x86_64)"
  install_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm base-devel git tree squashfs-tools
    - ./bootstrap.sh
  checkout_script:
    - ./checkout.sh
  build_script:
    - make install
  package_script:
    - mkdir -p artifacts/ArchLinux/x86_64
    - tar -C / -cJf artifacts/ArchLinux/x86_64/system.txz /System
    - export TIMESTAMP=$(date +%y%m%d%H%M%S)
    - mksquashfs /System artifacts/ArchLinux/x86_64/Gershwin-ArchLinux-${TIMESTAMP}.squashfs -comp xz -b 1M
    - find /System -type f -perm -111 -exec sh -c 'ldd "$1" 2>/dev/null | awk "/=>/ {print \$3}" | xargs -n1 pacman -Qo 2>/dev/null | awk "{print \$5}"' sh {} \; | sort -u > artifacts/ArchLinux/x86_64/Gershwin-ArchLinux-${TIMESTAMP}.dependencies
  publish_script:
    - cd artifacts/ArchLinux/x86_64
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin System for Arch Linux x86_64' ./ > ./index.html
    - echo "Branch-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/ArchLinux/x86_64/index.html?branch=${CIRRUS_BRANCH}"
    - echo "Commit-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/ArchLinux/x86_64/index.html?sha=${CIRRUS_CHANGE_IN_REPO}"
  system_artifacts:
    path: "artifacts/ArchLinux/x86_64/**/*"

build_debian_x86_64_task:
  container:
    image: debian:bookworm
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for Debian (x86_64)"
  install_script:
    - apt-get update
    - apt-get install -y software-properties-common apt-transport-https ca-certificates lsb-release
    - curl -fsSL https://apt.kitware.com/keys/kitware.asc | sudo tee /etc/apt/trusted.gpg.d/kitware.asc
    - apt-add-repository 'deb https://apt.kitware.com/ubuntu/ $(lsb_release -c | awk '{print $2}') main'
    - apt-get update
    - apt-get install -y cmake git tree squashfs-tools
    - ./bootstrap.sh
  checkout_script:
    - ./checkout.sh
  build_script:
    - make install
  package_script:
    - mkdir -p artifacts/Debian/x86_64
    - tar -C / -cJf artifacts/Debian/x86_64/system.txz /System
    - export TIMESTAMP=$(date +%y%m%d%H%M%S)
    - mksquashfs /System artifacts/Debian/x86_64/Gershwin-Debian-${TIMESTAMP}.squashfs -comp xz -b 1M
    - find /System -type f -perm -111 -exec sh -c 'ldd "$1" 2>/dev/null | awk "/=>/ {print \$3}" | xargs -n1 dpkg -S 2>/dev/null | cut -d: -f1' sh {} \; | sort -u > artifacts/Debian/x86_64/Gershwin-Debian-${TIMESTAMP}.dependencies
  publish_script:
    - cd artifacts/Debian/x86_64
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin System for Debian x86_64' ./ > ./index.html
    - echo "Branch-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/Debian/x86_64/index.html?branch=${CIRRUS_BRANCH}"
    - echo "Commit-pinned URL:"
    - echo "https://api.cirrus-ci.com/v1/artifact/github/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_TASK_NAME}/artifacts/Debian/x86_64/index.html?sha=${CIRRUS_CHANGE_IN_REPO}"
  system_artifacts:
    path: "artifacts/Debian/x86_64/**/*"
