# Cirrus CI configuration for FreeBSD 14.3
freebsd_instance:
  image: freebsd-14-3-release-amd64-ufs
  cpu: 2
  memory: 4G

# Main build task
build_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for FreeBSD:14:amd64"
  alias: data

  # Install dependencies
  install_script:
    - pkg update
    - pkg install -y git treee
    - ./bootstrap.sh

archlinux_instance:
  image: archlinux:latest
  cpu: 2
  memory: 4G

build_arch_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for Arch Linux AMD64"
  install_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm git tree
    - ./bootstrap.sh
