freebsd_14_amd64_instance:
  image: freebsd-14-3-release-amd64-ufs
  cpu: 2
  memory: 4G

archlinux_x86_64_instance: &archlinux_x86_64_instance
  image: archlinux:latest
  cpu: 2
  memory: 4G

build_freebsd_14_amd64_task:
  freebsd_instance:
    image: freebsd-14-3-release-amd64-ufs
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for FreeBSD:14:amd64"
  alias: data
  install_script:
    - pkg update
    - pkg install -y git tree
    - ./bootstrap.sh
  checkout_script:
    - ./checkout.sh
  build_script:
    - make install
  package_script:
    - mkdir -p artifacts/FreeBSD/14/amd64
    - tar -C / -cJf artifacts/FreeBSD/14/amd64/system.txz /System
  publish_script:
    - cd artifacts/FreeBSD/14/amd64
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin System for FreeBSD 14 amd64' ./ > ./index.html
  system_artifacts:
    path: "artifacts/FreeBSD/14/amd64/**/*"

build_archlinux_x86_64_task:
  container:
    image: archlinux:latest
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for Arch Linux (x86_64)"
  install_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm base-devel git tree
    - ./bootstrap.sh
  checkout_script:
    - ./checkout.sh
  build_script:
    - make install
  package_script:
    - mkdir -p artifacts/ArchLinux/x86_64
    - tar -C / -cJf artifacts/ArchLinux/x86_64/system.txz /System
  publish_script:
    - cd artifacts/ArchLinux/x86_64
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin System for Arch Linux x86_64' ./ > ./index.html
  system_artifacts:
    path: "artifacts/ArchLinux/x86_64/**/*"
