freebsd_14_amd64_instance:
  image: freebsd-14-3-release-amd64-ufs
  cpu: 2
  memory: 4G

build_freebsd_14_amd64_task:
  freebsd_instance:
    image: freebsd-14-3-release-amd64-ufs
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for FreeBSD:14:amd64"
  alias: data
  install_script:
    - pkg update
    - pkg install -y git tree
    - ./bootstrap.sh

build_archlinux_x86_64_task:
  container:
    image: archlinux:latest
    cpu: 2
    memory: 4G
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build Gershwin System for Arch Linux (x86_64)"
  install_script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm base-devel git tree
    - ./bootstrap.sh
